trigger:
- main

pool:
  vmImage: 'ubuntu-24.04'

steps:

- checkout: self

- task: UsePythonVersion@0
  displayName: 'Use Python 3.12'
  inputs:
    versionSpec: '3.12'

- script: |
    python --version
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest
  displayName: 'Install Dependencies'

- script: |
    echo "===== Current Directory ====="
    pwd

    echo "===== Project Files ====="
    find . -maxdepth 3 -type f -print

    echo "===== Checking app.py ====="
    ls -l app.py

    echo "===== Python Path ====="
    python -c "import sys; print('\n'.join(sys.path))"

    echo "===== Running Tests ====="
    export PYTHONPATH="$(pwd)"
    pytest -v
  displayName: 'Run Automated Tests'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    repository: azure-pipeline-demo
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
