trigger:
- main

pool:
  vmImage: ubuntu-24.04

steps:

- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest
  displayName: Install dependencies

- script: |
    echo "Current directory:"
    pwd
    echo "Repository files:"
    find . -maxdepth 2 -type f
  displayName: Verify files

- script: |
    pytest -v
  displayName: Run tests

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    repository: azure-pipeline-demo
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest